### ISSUE TITLE
Turning on BLTouch feature caused build to fail

### ISSUE THREAD

**Issue by mpturp** [mpturp/ModixTroubleshoot#1]
so when I went to activate the BLTouch feature for this printer (pulled from git link supplied by the board manufacturer), I started seeing this (and a couple other easily resolved) error. 

`Marlin\src\feature\touch\xpt2046.cpp: In static member function 'static void XPT2046::init()':
Marlin\src\feature\touch\../../inc/../HAL/./AVR/fastio.h:81:35: error: 'DIOCS_PIN_DDR' was not declared in this scope
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                   ^`

I can't seem to track down what's happening. The file the error links to has no commented callout for that "DIOCS_PIN_DDR" line that I can find, and I'm not sure I understand the structure here well enough to just go adding things in at random in hopes of repairing the issue. Any help is appreciated, and I'm happy to provide additional details as needed.

**Comment by mpturp** [comment]
Tagging US devs here, apologies if that's not the way things are done on git, i'm only just starting to actually use this account.
@thinkyhead @Roxy-3D @Bob-the-Kuhn

**Comment by thinkyhead** [comment]
I guess you figured it out. When you see an error referring to DIO…_DDR with a pin name stuck in the middle, it means that pin is not defined. If the pon was defined, it would produce a good symbol, such as DIO22_DDR.
